# Generated by Django 3.0.4 on 2020-04-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroku_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thecat',
            name='height_field',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thecat',
            name='width_field',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thecat',
            name='avatar',
            field=models.ImageField(height_field='height_field', upload_to='avatars', width_field='width_field'),
        ),
    ]
