# Generated by Django 3.0.4 on 2020-04-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroku_app', '0002_auto_20200414_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='thecat',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
