# Generated by Django 3.0.4 on 2020-04-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroku_app', '0004_auto_20200415_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thecat',
            name='logo',
        ),
        migrations.AlterField(
            model_name='thecat',
            name='avatar',
            field=models.ImageField(height_field='height_field', upload_to='avatars', width_field='width_field'),
        ),
    ]
