# Generated by Django 3.0.4 on 2020-04-15 10:56

from django.db import migrations, models
import heroku_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('heroku_app', '0005_auto_20200415_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='thecat',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thecat',
            name='avatar',
            field=models.ImageField(height_field='height_field', upload_to='avatars', validators=[heroku_app.models.validate_image], width_field='width_field'),
        ),
    ]
