# Generated by Django 3.0.4 on 2020-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroku_app', '0007_thecat_fluffy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mushroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13)),
                ('size', models.PositiveIntegerField()),
                ('poisonousness', models.BooleanField()),
            ],
        ),
    ]
