# Generated by Django 3.0.4 on 2020-05-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroku_app', '0008_mushroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('compliment', models.CharField(max_length=128)),
                ('date_of_delivery', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
